#!/usr/bin/env python
"""Generate the two reference pages that would otherwise drift: templates, API.

Both pages carry *code* — the shipped body of every analysis template, and the
signature of every function a notebook is invited to call. Copied by hand, both
go stale the first time someone edits a template or renames an argument, and a
documented call that no longer exists is worse than no documentation. So they
are derived: the template bodies come from the registry, the signatures from the
live objects, and ``tests/test_generated_docs.py`` fails if the checked-in pages
do not match what this script produces.

The prose lives *here*, in ``TEMPLATE_NOTES`` and ``API_ENTRIES``, not in the
generated markdown — regenerating must never destroy writing. Adding a template
without a note is a test failure, which is the point: the catalogue cannot
quietly fall behind the registry.

Usage::

    python scripts/generate_docs.py            # write the pages
    python scripts/generate_docs.py --check    # exit 1 if they are out of date
"""
from __future__ import annotations

import argparse
import difflib
import importlib
import inspect
import re
import sys
import textwrap
from dataclasses import dataclass, field
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DOCS = REPO / "docs"
SRC = REPO / "src"

if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

BANNER = (
    "<!-- Generated by scripts/generate_docs.py — do not edit by hand.\n"
    "     Prose lives in that script; run it again after changing a template\n"
    "     or the API allow-list. tests/test_generated_docs.py enforces this. -->"
)


# ══════════════════════════════════════════════════════════════════════════════
# Templates
# ══════════════════════════════════════════════════════════════════════════════

@dataclass(frozen=True)
class TemplateNote:
    """The hand-written half of a template's documentation."""

    group: str          # heading the template is filed under
    tab: str            # GUI tab that runs it, as a wiki link
    what: str           # what the analysis computes, in prose
    reading: str = ""   # how to read the code / why it is shaped this way
    variants: str = ""  # what the assemblies mean, when there is more than one


# Ordered: the reader meets setup first, then the analyses that depend on it.
TEMPLATE_NOTES: dict[str, TemplateNote] = {
    "normalize": TemplateNote(
        group="Setup",
        tab="every expression-based tab",
        what=(
            "Builds `adata_norm`, the normalised copy that every expression-based "
            "analysis reads: counts per cell scaled to 10,000, `log1p`, then PCA. "
            "Nothing else normalises, and nothing normalises `adata` in place."
        ),
        reading=(
            "The copy is the whole point. An earlier version normalised `adata` "
            "itself, which made the provenance graph lie: a step that read "
            "`adata` got different numbers depending on whether some other tab "
            "had run first. Every downstream template declares `deps=[\"normalize\"]` "
            "and reads `adata_norm`, so the dependency is explicit and the "
            "notebook reproduces it in the right order. `ctx.ensure_normalized()` "
            "is idempotent — running it twice does not re-normalise."
        ),
    ),
    "spatial_neighbors": TemplateNote(
        group="Setup",
        tab="[Neighborhood Enrichment](Tab-Neighborhood-Enrichment) and "
            "[Ligand-Receptor](Tab-Ligand-Receptor)",
        what=(
            "Builds the spatial neighbour graph squidpy's spatial statistics need, "
            "on `adata_norm`, from each cell's *k* nearest neighbours. Uses "
            "`spatial_neighbors_knn`, which replaced "
            "`spatial_neighbors(coord_type='generic')` — removed in squidpy 1.9. "
            "The two produce an identical graph, so results recorded before the "
            "change still match."
        ),
        reading=(
            "This is the one template with no live preview in the "
            "[Templates](Tab-Templates) tab. *k* comes from whichever tab called "
            "`ctx.ensure_spatial_neighbors()`, and two tabs have their own slider, "
            "so a preview provider would have to pick one of them arbitrarily. It "
            "declares a `sample-params` value instead and the preview says so."
        ),
    ),
    "clustering.leiden": TemplateNote(
        group="Clustering",
        tab="[Clustering](Tab-Clustering)",
        what=(
            "Leiden community detection on a copy of `adata_norm`, writing the "
            "labels back to `adata.obs[key]`. The result is what every "
            "cluster-keyed analysis — ranked genes, neighbourhood enrichment, "
            "co-occurrence, ligand-receptor — is grouped by."
        ),
        reading=(
            "`leiden_labels` is a declared output rather than something read back "
            "off `ctx.adata` afterwards. That matters: reading back worked only "
            "while the executor namespace and `ctx.adata` were the same object, "
            "and the executor now raises if a template stops binding a declared "
            "output, so an edit that breaks the result fails loudly."
        ),
        variants=(
            "The four assemblies are the four combinations of the two "
            "preprocessing checkboxes. Highly-variable-gene selection adds `hvg`, "
            "scaling adds `scale`, and either one adds `pca` — because PCA has to "
            "be recomputed once the matrix has changed. With neither, the PCA "
            "already computed by `normalize` is reused and only `head+tail` runs."
        ),
    ),
    "genes.rank_genes": TemplateNote(
        group="Genes",
        tab="[Rank Genes](Tab-Rank-Genes)",
        what=(
            "Ranks marker genes per cluster with `sc.tl.rank_genes_groups`, and "
            "returns the result as a tidy DataFrame."
        ),
        reading=(
            "Note `key_added=$rank_key`. scanpy writes `uns['rank_genes_groups']` "
            "in place, so ranking a second clustering used to overwrite the first "
            "— a session that ranked two clusterings ended holding markers for "
            "whichever ran last. Keying per clustering is also what lets the "
            "`sc.pl.rank_genes_groups*` plots reach a specific result, since they "
            "all take `key=`."
        ),
    ),
    "genes.marker_plot": TemplateNote(
        group="Genes",
        tab="[Markers](Tab-Markers)",
        what=(
            "Draws one scanpy marker-gene figure — dotplot, heatmap, matrixplot, "
            "tracksplot or correlation matrix — for a set of genes grouped by a "
            "clustering, and saves it."
        ),
        variants=(
            "Ten assemblies: which of the five `call.*` plot types you picked, "
            "times whether the clusters have been given names (`relabel`). There "
            "used to be twenty — a second axis for whether the save carried "
            "`dpi=150` — but the output format is no longer a per-plot choice: "
            "the `save` block loops over a `paths` list holding one file per "
            "format Preferences asks for."
        ),
    ),
    "umap.plot": TemplateNote(
        group="Genes",
        tab="[UMAP](Tab-UMAP)",
        what=(
            "Draws the UMAP embedding as a publication figure — one panel per "
            "selected gene, each with its own colour scale, or a single panel "
            "coloured by a clustering with the labels drawn on the points."
        ),
        reading=(
            "`embed.xenium` reads `analysis/umap/gene_expression_2_components/"
            "projection.csv`, which is where the viewer's own UMAP window gets "
            "its coordinates. That matters more than it looks: recomputing the "
            "embedding with `sc.tl.umap` gives an equally valid layout that is "
            "not the one that was on screen, so the notebook would disagree with "
            "the session it claims to reproduce."
        ),
        variants=(
            "Six assemblies from three choices: whether the dataset ships "
            "Xenium's UMAP or the embedding has to be recomputed (a Crop Dataset "
            "export has no `analysis/` folder), whether the colour is a list of "
            "genes or a clustering, and whether that clustering's clusters have "
            "been given names."
        ),
    ),
    "genes.correlation": TemplateNote(
        group="Genes",
        tab="[Gene Correlation](Tab-Gene-Correlation)",
        what=(
            "Scatters two genes cell by cell, annotates Pearson and Spearman "
            "coefficients with p-values, and saves the figure."
        ),
        reading=(
            "The `expr.fraction` block calls `sc.pp.calculate_qc_metrics` with "
            "`inplace=False` on purpose. With `inplace=True` scanpy overwrites "
            "`obs['total_counts']` — one of Xenium's own columns — so the template "
            "would mutate `adata` on its way to reading a total. A template must "
            "not change the data it is describing."
        ),
        variants=(
            "Six assemblies: three normalisations (raw counts, fraction of the "
            "cell's total, log1p CPM from `adata_norm`) times whether a cluster "
            "subset is selected, which adds the `filter` block and changes the "
            "title to say the count is filtered."
        ),
    ),
    "genes.cnv_infercnv": TemplateNote(
        group="Genes",
        tab="[CNV](Tab-CNV)",
        what=(
            "Infers copy-number variation against a reference population with "
            "inferCNV, in-process: prepares the input, builds CNV neighbours, "
            "clusters at several resolutions and scores each cell."
        ),
        reading=(
            "`arrow_shim` is a **frozen block** — it cannot be customised even "
            "with overrides enabled. It is a version workaround whose byte "
            "identity with a helper elsewhere is pinned by a test, and no "
            "validation gate could have told you that editing it breaks on the "
            "next pandas. The [Templates](Tab-Templates) tab lists frozen blocks "
            "in the Contract pane for exactly this reason."
        ),
        variants=(
            "Two assemblies, differing only in whether a subset of clusters was "
            "selected to run on."
        ),
    ),
    "spatial.nhood": TemplateNote(
        group="Spatial",
        tab="[Neighborhood Enrichment](Tab-Neighborhood-Enrichment)",
        what=(
            "Squidpy's neighbourhood-enrichment permutation test: which cluster "
            "pairs are adjacent more or less often than chance, as z-scores."
        ),
        reading=(
            "Needs the graph from `spatial_neighbors` first; the tab calls "
            "`ctx.ensure_spatial_neighbors(k)` before running this, and the "
            "provenance graph records the dependency."
        ),
    ),
    "spatial.cooccur": TemplateNote(
        group="Spatial",
        tab="[Co-occurrence](Tab-Co-occurrence)",
        what=(
            "Squidpy's co-occurrence score across increasing radii — how the "
            "probability of finding one cluster near another changes with "
            "distance."
        ),
    ),
    "spatial.ligrec": TemplateNote(
        group="Spatial",
        tab="[Ligand-Receptor](Tab-Ligand-Receptor)",
        what=(
            "Squidpy's ligand-receptor permutation test over the omnipath "
            "interaction database, between the clusters of a chosen clustering."
        ),
        variants=(
            "Four assemblies: whether specific interaction datasets are included, "
            "and whether resources are restricted — each adds its own block that "
            "fills in `interactions_params`."
        ),
    ),
    "roi.polygons": TemplateNote(
        group="ROI",
        tab="[ROI Analysis](Tab-ROI-Analysis)",
        what=(
            "Inlines the polygons you drew in the viewer as literal coordinates, "
            "so the notebook reproduces the exact regions without needing the "
            "napari shapes layer."
        ),
        reading=(
            "Two deliberate details. napari stores shapes as N×2 `(y, x)` pixel "
            "arrays, and the flip to `(x, y)` happens **once**, here — an earlier "
            "version flipped and unflipped on consecutive lines, so the comment "
            "asserted a convention the code reversed. And `make_valid`, not "
            "`buffer(0)`: on a self-intersecting ROI `buffer(0)` silently deletes "
            "a lobe rather than repairing it."
        ),
    ),
    "roi.deg": TemplateNote(
        group="ROI",
        tab="[ROI Analysis](Tab-ROI-Analysis)",
        what=(
            "Differential expression between the regions you drew: assigns cells "
            "to ROIs, then ranks genes across them."
        ),
        reading=(
            "The centroid-to-ROI test goes through `sd.models.PointsModel.parse` "
            "and `sd.polygon_query` rather than a hand-rolled point-in-polygon "
            "loop. `adata.obsm['spatial']` is in microns and the ROIs are in "
            "pixels; the scale between them is **declared** as a spatialdata "
            "transformation instead of applied by hand, which is what keeps the "
            "notebook's coordinate conventions honest."
        ),
        variants=(
            "Two assemblies, differing in whether the analysis is restricted to "
            "selected clusters."
        ),
    ),
    "roi.expression": TemplateNote(
        group="ROI",
        tab="[ROI Analysis](Tab-ROI-Analysis)",
        what=(
            "Per-region expression of a single gene, with summary statistics per "
            "ROI and pairwise Welch t-tests between every pair of regions, "
            "Benjamini-Hochberg corrected."
        ),
        reading=(
            "The Welch + BH block is hand-rolled numpy/scipy rather than a "
            "library call, and says so in a comment. That is allowed where no API "
            "covers the case — the rule is to prefer the library where one "
            "exists, not to avoid writing statistics."
        ),
        variants=(
            "Two assemblies, as for `roi.deg`: with or without a cluster filter."
        ),
    ),
    "roi.export_expression": TemplateNote(
        group="ROI",
        tab="[ROI Analysis](Tab-ROI-Analysis)",
        what=(
            "Writes the per-cell ROI expression table produced by "
            "`roi.expression` to CSV."
        ),
        reading=(
            "A terminal step: it produces a file, not a value, so nothing depends "
            "on it. Its preview renders the filename the save dialog would "
            "propose, and the preview header says the path is a sample — a value "
            "that cannot come from a widget is named rather than faked."
        ),
    ),
}

GROUP_ORDER = ["Setup", "Clustering", "Genes", "Spatial", "ROI"]

TEMPLATES_INTRO = """\
# Analysis Templates

Every analysis the viewer runs is a **template**: a piece of plain scverse source
with a declared contract, kept in `src/xenium_viewer/utils/step_templates/builtin/`
as a `.tmpl` file. When you click a button, the owning tab builds a dictionary of
parameters, the template is rendered once, and *that same string* is both executed
and recorded in the provenance graph — so the code below is the code that runs,
and the code the exported notebook replays.

This page is the catalogue: what each template computes, its contract, and its
full default source. It is generated from the registry itself, so it cannot
disagree with what is installed.

- To **change** any of this, see the [Templates](Tab-Templates) tab — overrides
  are resolved per block, so you can edit one step without freezing the rest.
- To **see what a specific run did**, see the [Notebook](Tab-Notebook) tab; the
  provenance graph records the rendered code, not the template.
- The API behind all of it is in the [API Reference](API-Reference).

## How to read a template

A template is an ordered set of **named blocks**, delimited by `#--- block <name>`
lines. Everything structural is a comment, so the file is valid Python.

| Contract field | Meaning |
|---|---|
| `params` | The `$name` placeholders the template expects. A `?` marks an optional one. Values are substituted as Python literals. |
| `requires` | Names the template may use from the executor namespace — `sc`, `sq`, `sd`, `pd`, `np`, `plt`, `Path`, `data_path`, `sdata`, `adata`, plus anything a declared dependency binds. Referencing anything else is rejected before it can fail as a `NameError` on replay. |
| `outputs` | Results the template must bind. The executor raises if one is missing, so a template edit that stops producing a result fails immediately instead of returning stale state. |
| `assemblies` | The block combinations that are allowed to run. The **call site** decides which one to use, because the branch structure is what the widgets mean; the registry owns the text. |
| frozen blocks | Blocks that may not be customised, listed where they occur. |

Which assembly runs is decided by the tab, from your widget settings. The
[Templates](Tab-Templates) tab's preview pane shows the exact assembled and
substituted string for the settings currently in the owning tab.
"""


def _anchor(heading: str) -> str:
    """A same-page link target, by GitHub's rules.

    Lowercase, punctuation dropped, spaces to hyphens — but **underscores are
    kept**, which is the part that is easy to get wrong: `spatial_neighbors`
    anchors as `#spatial_neighbors`, not `#spatial-neighbors`.
    """
    slug = re.sub(r"[^\w\s-]", "", heading.lower())
    return "#" + re.sub(r"\s+", "-", slug.strip())


def _fence(text: str) -> str:
    """A python code fence, with the template's leading blank line trimmed."""
    return "```python\n" + text.strip("\n") + "\n```"


def _source(spec) -> str:
    """The template body, with its block markers.

    ``builtin_text`` concatenates every block, which for a multi-block template
    means mutually exclusive variants run together — `clustering.leiden` would
    read as HVG *and* scaling *and* PCA, an assembly that never runs. Showing the
    markers is how the `.tmpl` file actually looks and how the Templates tab
    shows it, so the reader can see which lines belong to which variant.
    """
    if len(spec.blocks) == 1:
        return _fence(next(iter(spec.blocks.values())).text)
    parts = []
    for name, block in spec.blocks.items():
        marker = f"#--- block {name}"
        if not block.editable:
            marker += "        # frozen: not customisable"
        parts.append(marker + "\n" + block.text.strip("\n"))
    return _fence("\n\n".join(parts))


def _params_table(spec) -> str:
    if not spec.params:
        return "_No parameters._"
    rows = ["| Parameter | Type | Required |", "|---|---|---|"]
    for p in spec.params:
        rows.append(f"| `{p.name}` | `{p.type}` | {'yes' if p.required else 'no'} |")
    return "\n".join(rows)


def _assemblies(spec) -> str:
    if len(spec.assemblies) <= 1:
        return ""
    lines = [f"- `{' + '.join(a)}`" for a in spec.assemblies]
    return "\n".join(lines)


def render_templates_page() -> str:
    # builtin_* on purpose: this page documents the *shipped* defaults, and the
    # builtin readers cannot see a user override, so it says what everyone gets
    # rather than what this machine's config resolves to. Run sites must use
    # step_template() instead — test_every_step_resolves_user_overrides checks
    # that — but a catalogue of defaults is the one place the rule inverts.
    from xenium_viewer.utils.step_templates import loader as registry

    ids = registry.builtin_ids()
    missing = sorted(set(ids) - set(TEMPLATE_NOTES))
    if missing:
        raise SystemExit(
            f"No prose for template(s) {missing} — add a TemplateNote in "
            f"{Path(__file__).name} before regenerating."
        )

    out = [BANNER, "", TEMPLATES_INTRO.rstrip(), ""]

    by_group: dict[str, list[str]] = {g: [] for g in GROUP_ORDER}
    for tid in ids:
        by_group[TEMPLATE_NOTES[tid].group].append(tid)

    out.append("## Contents\n")
    for group in GROUP_ORDER:
        for tid in by_group[group]:
            # The one-line summary is the template's own `doc:` header — written
            # for exactly this, and guaranteed to match the file. Deriving it by
            # truncating the prose at the first "." cut `adata.obs` in half.
            out.append(f"- [`{tid}`]({_anchor(tid)}) — "
                       f"{registry.builtin_spec(tid).doc}")
    out.append("")

    for group in GROUP_ORDER:
        out.append(f"## {group}\n")
        for tid in by_group[group]:
            note = TEMPLATE_NOTES[tid]
            spec = registry.builtin_spec(tid)
            out.append(f"### `{tid}`\n")
            out.append(f"**Run by:** {note.tab}\n")
            out.append(f"{note.what}\n")
            if note.reading:
                out.append(f"{note.reading}\n")
            out.append("**Contract**\n")
            out.append(_params_table(spec) + "\n")
            requires = ", ".join(f"`{n}`" for n in sorted(spec.requires)) or "_nothing_"
            outputs = ", ".join(f"`{n}`" for n in spec.outputs) or "_nothing (terminal step)_"
            out.append(f"- **Requires:** {requires}")
            out.append(f"- **Outputs:** {outputs}")
            blocks = ", ".join(f"`{n}`" for n in spec.blocks)
            out.append(f"- **Blocks:** {blocks}")
            frozen = [n for n, b in spec.blocks.items() if not b.editable]
            if frozen:
                out.append("- **Frozen (not customisable):** "
                           + ", ".join(f"`{n}`" for n in frozen))
            out.append("")
            if len(spec.assemblies) > 1:
                out.append(f"**Variants** — {len(spec.assemblies)} assemblies:\n")
                if note.variants:
                    out.append(note.variants + "\n")
                out.append(_assemblies(spec) + "\n")
            label = ("**Default source**" if len(spec.blocks) == 1
                     else "**Default source** — by block; an assembly above picks "
                          "which of these run, in that order")
            out.append(label + "\n")
            out.append(_source(spec) + "\n")

    return "\n".join(out).rstrip() + "\n"


# ══════════════════════════════════════════════════════════════════════════════
# API reference
# ══════════════════════════════════════════════════════════════════════════════

@dataclass(frozen=True)
class ApiEntry:
    """One documented callable: where it lives, what it does, how to call it."""

    module: str
    name: str
    what: str
    snippet: str = ""
    caveat: str = ""


@dataclass(frozen=True)
class ApiSection:
    title: str
    intro: str
    entries: list[ApiEntry] = field(default_factory=list)


API_INTRO = """\
# API Reference

Most of what the viewer does is available as ordinary Python. The analysis
functions take a plain `AnnData` and return plain results, so a notebook can call
them directly — useful for batching across datasets, for re-running one step with
parameters the GUI does not expose, or for picking up where an exported notebook
left off.

```python
import sys
sys.path.insert(0, "/path/to/xenium_viewer/src")   # or: pip install -e .

from xenium_viewer import loader
from xenium_viewer.utils import gene_analysis, spatial_analysis
```

Installing the package (`pip install -e .`, which `environment.yml` does for you)
makes the `sys.path` line unnecessary.

## What is and is not API

Everything on this page takes ordinary arguments and works without a GUI. The
codebase contains a great deal more that is public in the Python sense but is
really viewer internals — it takes a `ViewerContext`, mutates napari layers, or
assumes a Qt event loop. Those are listed under
[Reachable, but needs a live viewer](#reachable-but-needs-a-live-viewer) rather
than documented as API, because depending on them from a notebook will not go
well.

Signatures below are extracted from the live objects when this page is generated,
so they cannot describe a function that no longer exists.

> **`load_sdata` writes to disk.** On a cache miss it *builds*
> `sdata_cached.zarr` next to the dataset, which takes minutes and tens of GB of
> disk, and it may prompt about a stale cache. Pass `use_cache=False` for a
> read-only load that touches nothing.

A few defaults below are `Path`s resolved against the working directory at import
time; they are shown as `.../name`, since the absolute value depends on where the
interpreter was started and is not something to rely on. Pass those explicitly.
"""

API_SECTIONS: list[ApiSection] = [
    ApiSection(
        title="Loading a dataset",
        intro=(
            "The same entry points the viewer uses at startup. `load_sdata` "
            "returns a `SpatialData`; the table is `sdata.tables['table']`, an "
            "ordinary `AnnData`, which is what every analysis function below "
            "expects."
        ),
        entries=[
            ApiEntry(
                "xenium_viewer.loader", "load_sdata",
                "Load a Xenium output directory, through the zarr cache when there "
                "is one. With a cache this takes seconds rather than the minutes a "
                "cold `spatialdata_io.xenium()` needs, and the pyramid levels come "
                "back read from disk rather than as a lazy `coarsen()` chain — "
                "which is the difference between a 1.7 GB and a 23 GB peak the "
                "moment you touch a low-resolution level. `on_stale` answers the "
                "stale-cache question in advance (`'keep'`, `'rebuild'` or "
                "`'restore'`) instead of prompting, which is what makes the load "
                "usable with no GUI attached; the `xenium-build-cache` console "
                "script is this function with that flag exposed.",
                snippet=(
                    "from pathlib import Path\n"
                    "from xenium_viewer import loader\n\n"
                    "sdata = loader.load_sdata(Path('/data/xenium_run'))\n"
                    "adata = sdata.tables['table']\n"
                    "print(adata)"
                ),
                caveat="Builds and writes the cache on a miss; `use_cache=False` avoids that.",
            ),
            ApiEntry(
                "xenium_viewer.loader", "load_clusterings",
                "The clusterings 10x shipped with the run, read from the output's "
                "`analysis/clustering/` directory — `graphclust`, the `kmeans_*` "
                "series — as a dict of name to a Series indexed by cell barcode. "
                "Takes the **dataset path**, not an AnnData, and returns `{}` when "
                "there is no `analysis/` folder, which is the case for a Crop "
                "Dataset export. Clusterings *you* computed live in "
                "`adata.obs`, not here.",
                snippet=(
                    "clusterings = loader.load_clusterings(Path('/data/xenium_run'))\n"
                    "list(clusterings)          # [] for a cropped export\n\n"
                    "# Your own clusterings are obs columns on the table:\n"
                    "[c for c in adata.obs.columns if c.startswith('clustering_')]"
                ),
            ),
            ApiEntry(
                "xenium_viewer.loader", "load_umap",
                "The UMAP embedding from the Xenium output's own `analysis/` "
                "directory, if the run produced one.",
            ),
            ApiEntry(
                "xenium_viewer.loader", "get_label_to_obs_mapping",
                "Map label-raster values to row positions in `adata.obs`. This is "
                "what turns a pixel you clicked into a cell, and it is needed "
                "whenever you colour the segmentation raster by a per-cell value.",
            ),
            ApiEntry(
                "xenium_viewer.utils.transcript_index", "TranscriptLoader",
                "Per-gene transcript access. With the feather index built by "
                "`xenium-preprocess` a gene loads in ~100 ms; without it, each "
                "query falls back to scanning `transcripts.parquet` and takes "
                "seconds. `cached_genes` is a property, not a method, and is "
                "empty when the index has not been built.",
                snippet=(
                    "from pathlib import Path\n"
                    "from xenium_viewer.utils.transcript_index import TranscriptLoader\n\n"
                    "run = Path('/data/xenium_run')\n"
                    "tl = TranscriptLoader(cache_dir=run / 'transcript_cache',\n"
                    "                      parquet_path=run / 'transcripts.parquet')\n"
                    "print(len(tl.cached_genes))     # 0 if xenium-preprocess never ran\n"
                    "df = tl.load_gene('EPCAM')      # x, y, and quality columns"
                ),
            ),
        ],
    ),
    ApiSection(
        title="Expression analysis",
        intro=(
            "These take the **normalised** AnnData. Build it the way the templates "
            "do — `sc.pp.normalize_total(target_sum=1e4)`, `sc.pp.log1p`, "
            "`sc.pp.pca` on a copy — or read the [normalize](Analysis-Templates#normalize) "
            "template for the exact three lines."
        ),
        entries=[
            ApiEntry(
                "xenium_viewer.utils.gene_analysis", "run_rank_genes",
                "Rank marker genes per cluster and return them as a tidy DataFrame, "
                "one row per gene per group.",
                snippet=(
                    "import scanpy as sc\n"
                    "from xenium_viewer.utils import gene_analysis\n\n"
                    "adata_norm = adata.copy()\n"
                    "sc.pp.normalize_total(adata_norm, target_sum=1e4)\n"
                    "sc.pp.log1p(adata_norm)\n"
                    "sc.pp.pca(adata_norm)\n\n"
                    "# Clusterings the viewer saved are obs columns named clustering_*\n"
                    "groupby = next(c for c in adata.obs.columns\n"
                    "               if c.startswith('clustering_'))\n"
                    "df = gene_analysis.run_rank_genes(adata_norm, groupby=groupby)\n"
                    "df.head()"
                ),
            ),
            ApiEntry(
                "xenium_viewer.utils.gene_analysis", "rank_genes_key",
                "The `uns` key a ranking is stored under for a given clustering. "
                "Rankings are keyed per clustering so a second one does not "
                "overwrite the first — use this rather than assuming "
                "`'rank_genes_groups'`.",
            ),
            ApiEntry(
                "xenium_viewer.utils.gene_analysis", "resolve_rank_key",
                "Find the ranking actually present for a clustering, falling back "
                "to the unkeyed default for results saved before keying existed.",
            ),
            ApiEntry(
                "xenium_viewer.utils.gene_analysis", "add_clustering_to_obs",
                "Attach a clustering to `adata.obs` under the viewer's naming "
                "conventions, so the GUI and the session store recognise it.",
            ),
            ApiEntry(
                "xenium_viewer.utils.gene_analysis", "make_rank_genes_dotplot",
                "The dotplot the Markers tab draws, as a matplotlib figure.",
            ),
            ApiEntry(
                "xenium_viewer.utils.gene_analysis", "run_celltypist_annotation",
                "Annotate cell types with CellTypist against a downloaded "
                "reference model.",
            ),
        ],
    ),
    ApiSection(
        title="Spatial statistics",
        intro=(
            "Thin, honest wrappers over squidpy: they build the neighbour graph "
            "the way the viewer does and return the results rather than plotting "
            "them. Call `compute_spatial_neighbors` first — the others need the "
            "graph."
        ),
        entries=[
            ApiEntry(
                "xenium_viewer.utils.spatial_analysis", "compute_spatial_neighbors",
                "Build the spatial neighbour graph on the normalised AnnData. "
                "Mutates `adata_norm` in place, as squidpy does.",
                snippet=(
                    "from xenium_viewer.utils import spatial_analysis as sa\n\n"
                    "sa.compute_spatial_neighbors(adata_norm, n_neighs=6)\n"
                    "res = sa.run_nhood_enrichment(adata_norm, cluster_key=groupby,\n"
                    "                              n_perms=100)\n"
                    "res['zscore'].shape"
                ),
            ),
            ApiEntry(
                "xenium_viewer.utils.spatial_analysis", "run_nhood_enrichment",
                "Neighbourhood-enrichment permutation test: which cluster pairs "
                "are adjacent more or less often than chance.",
            ),
            ApiEntry(
                "xenium_viewer.utils.spatial_analysis", "make_nhood_enrichment_plot",
                "The enrichment heatmap, as a figure.",
            ),
            ApiEntry(
                "xenium_viewer.utils.spatial_analysis", "make_co_occurrence_plot",
                "The co-occurrence-versus-radius plot, as a figure.",
            ),
            ApiEntry(
                "xenium_viewer.utils.spatial_analysis", "make_ligrec_plot",
                "The ligand-receptor dotplot, as a figure.",
            ),
        ],
    ),
    ApiSection(
        title="Copy number",
        intro=(
            "inferCNV runs in the main environment. CopyKAT does not — it needs "
            "rpy2 and R 4.3, which pin python 3.11, so it runs in the separate "
            "`xenium_viewer_copykat` environment via a detached worker. From a "
            "notebook in the main environment, use `backend='infercnv'`."
        ),
        entries=[
            ApiEntry(
                "xenium_viewer.utils.cnv_analysis", "run_cnv_pipeline",
                "Infer CNV against a reference population and cluster the result.",
                snippet=(
                    "from xenium_viewer.utils import cnv_analysis\n\n"
                    "result = cnv_analysis.run_cnv_pipeline(\n"
                    "    adata,\n"
                    "    reference_series=adata.obs['leiden'],\n"
                    "    reference_categories=['0', '3'],   # the normal clusters\n"
                    "    backend='infercnv',\n"
                    ")"
                ),
            ),
            ApiEntry(
                "xenium_viewer.utils.cnv_analysis", "check_gene_mapping",
                "How many panel genes map to genomic positions — worth checking "
                "before a run, since a Xenium panel covers a few hundred genes and "
                "coverage per chromosome arm drives whether the result means "
                "anything.",
            ),
            ApiEntry(
                "xenium_viewer.utils.cnv_analysis", "make_cnv_heatmap",
                "The chromosome-ordered CNV heatmap, as a figure.",
            ),
        ],
    ),
    ApiSection(
        title="Image registration",
        intro=(
            "The maths behind the H&E and ARMS overlays. Landmark pairs in, "
            "similarity affine out — usable on any two images, not just the ones "
            "the viewer loads."
        ),
        entries=[
            ApiEntry(
                "xenium_viewer.utils.registration", "compute_landmark_affine",
                "Least-squares similarity transform (rotation, uniform scale, "
                "translation) from matched landmark pairs.",
                snippet=(
                    "import numpy as np\n"
                    "from xenium_viewer.utils import registration\n\n"
                    "fixed  = np.array([[100, 200], [800, 250], [450, 900]])\n"
                    "moving = np.array([[110, 190], [810, 260], [460, 880]])\n"
                    "affine = registration.compute_landmark_affine(moving, fixed)"
                ),
            ),
            ApiEntry(
                "xenium_viewer.utils.registration", "load_he_pyramid",
                "Read an H&E slide as a multiscale pyramid, lazily.",
            ),
            ApiEntry(
                "xenium_viewer.utils.registration", "load_multichannel_pyramid",
                "The same for a multi-channel fluorescence image.",
            ),
            ApiEntry(
                "xenium_viewer.utils.registration", "save_landmarks",
                "Persist landmark pairs beside the dataset.",
            ),
            ApiEntry(
                "xenium_viewer.utils.registration", "load_landmarks",
                "Read them back.",
            ),
            ApiEntry(
                "xenium_viewer.utils.registration", "extract_tissue_mask",
                "Segment tissue from background, for a coarse initial alignment.",
            ),
        ],
    ),
    ApiSection(
        title="Cache, storage and persistence",
        intro=(
            "**Never write to the zarr store directly.** Every element write goes "
            "through the staging-and-rename path in `zarr_safe`, which journals "
            "the operation and moves the previous copy to `.xv_trash/` rather than "
            "deleting it. Writing straight to the store leaves it invalid if "
            "anything interrupts."
        ),
        entries=[
            ApiEntry(
                "xenium_viewer.utils.cache_repair", "verify",
                "Read-only health check of a cache. Parses the root `zarr.json` "
                "with `json.loads` rather than opening the store, so it works on "
                "one too broken to open.",
                snippet=(
                    "from pathlib import Path\n"
                    "from xenium_viewer.utils import cache_repair\n\n"
                    "report = cache_repair.verify(Path('/data/xenium_run/sdata_cached.zarr'))\n"
                    "print(report.ok, report.missing_on_disk)"
                ),
            ),
            ApiEntry(
                "xenium_viewer.utils.cache_repair", "repair",
                "Fix what `verify` found. Only renames, clears debris and "
                "re-consolidates — it never deletes a cache.",
            ),
            ApiEntry(
                "xenium_viewer.utils.cache_repair", "describe_store",
                "A human-readable summary of what is in a store.",
            ),
            ApiEntry(
                "xenium_viewer.utils.store_inventory", "build_inventory",
                "Everything on disk for a dataset — raw output, cache elements, "
                "session state, derived caches, backups — with sizes and an honest "
                "`recoverable` flag per node. Filesystem-only and read-only.",
                snippet=(
                    "from xenium_viewer.utils import store_inventory\n\n"
                    "for section in store_inventory.build_inventory(Path('/data/xenium_run')):\n"
                    "    total = sum(n.size_bytes for n in section.nodes)\n"
                    "    print(f'{section.title:24s} {total / 2**30:6.2f} GiB')"
                ),
            ),
            ApiEntry(
                "xenium_viewer.utils.sdata_write", "write_sdata",
                "Write a `SpatialData` one element at a time, capping dask's "
                "concurrency where the intermediates are large and releasing "
                "memory between elements. Interchangeable with "
                "`SpatialData.write()` — a test asserts the stores match — but it "
                "reports progress and holds a far lower peak.",
                snippet=(
                    "from xenium_viewer.utils import sdata_write\n\n"
                    "sdata_write.write_sdata(sdata, Path('/tmp/out.zarr'),\n"
                    "                        progress_cb=lambda pct, msg: print(pct, msg))"
                ),
            ),
            ApiEntry(
                "xenium_viewer.utils.adata_persistence", "sidecar_write_path",
                "Where a derived result belongs: `<data_path>/viewer_cache/`, not "
                "the zarr store root. Files in the store root make zarr's "
                "hierarchy walk warn on every consolidation, and a rebuild deletes "
                "them.",
            ),
            ApiEntry(
                "xenium_viewer.utils.adata_persistence", "find_sidecar",
                "Read one back, falling back to the legacy in-store location for "
                "datasets that predate the move.",
            ),
            ApiEntry(
                "xenium_viewer.utils.session", "load_session",
                "Read the viewer session — ROIs, registrations, clusterings, DEG "
                "results, the provenance graph — out of a cache without starting "
                "the GUI.",
            ),
        ],
    ),
    ApiSection(
        title="Provenance and notebooks",
        intro=(
            "The provenance graph is the single source of truth for reproducible "
            "code: a DAG of steps, each with a stable id, its rendered code and "
            "its dependencies. The notebook is *derived* from it by topological "
            "sort, so it respects dependencies regardless of the order you "
            "clicked things — even across sessions."
        ),
        entries=[
            ApiEntry(
                "xenium_viewer.utils.prov_graph", "ProvGraph",
                "The DAG itself: `upsert(node_id, code, deps=…)` adds or revises a "
                "step and flags its descendants stale; a missing dependency errors "
                "at record time rather than at replay. `topo_sort()` returns node "
                "**ids**, in dependency order; `get(node_id)` gives the node.",
                snippet=(
                    "import json\n"
                    "from pathlib import Path\n"
                    "from xenium_viewer.utils.prov_graph import ProvGraph\n\n"
                    "sidecar = Path('/data/xenium_run/viewer_cache/prov_graph.json')\n"
                    "graph = ProvGraph.from_list(json.loads(sidecar.read_text()))\n\n"
                    "for node_id in graph.topo_sort():\n"
                    "    print(node_id, '<-', graph.get(node_id).deps)"
                ),
            ),
            ApiEntry(
                "xenium_viewer.utils.prov_graph", "graph_to_script",
                "Render the graph as a flat `analysis.py`.",
            ),
            ApiEntry(
                "xenium_viewer.utils.prov_graph", "graph_to_mermaid",
                "Render the DAG as mermaid diagram text.",
            ),
            ApiEntry(
                "xenium_viewer.utils.notebook_export", "write_graph_notebook",
                "Write the graph out as a real `.ipynb`. The notebook is code-only "
                "and replays from the raw Xenium output.",
                snippet=(
                    "from xenium_viewer.utils import notebook_export\n\n"
                    "notebook_export.write_graph_notebook(graph, Path('analysis.ipynb'))"
                ),
            ),
            ApiEntry(
                "xenium_viewer.utils.notebook_export", "execute_notebook",
                "Execute a notebook in a throwaway kernelspec pointing at "
                "`sys.executable` — deliberately not the installed `python3` "
                "kernel, which on a conda box belongs to whichever environment "
                "registered it last.",
            ),
            ApiEntry(
                "xenium_viewer.utils.notebook_export", "customisation_banner",
                "The markdown cell prepended when any step ran from a "
                "non-shipped template.",
            ),
        ],
    ),
    ApiSection(
        title="The template registry",
        intro=(
            "Read the shipped templates, or resolve them the way the viewer does "
            "with user overrides applied. See [Analysis Templates](Analysis-Templates) "
            "for what each one contains."
        ),
        entries=[
            ApiEntry(
                "xenium_viewer.utils.step_templates.loader", "builtin_ids",
                "Every shipped template id.",
                snippet=(
                    "from xenium_viewer.utils.step_templates import loader as registry\n\n"
                    "for tid in registry.builtin_ids():\n"
                    "    spec = registry.builtin_spec(tid)\n"
                    "    print(tid, '->', spec.doc)"
                ),
            ),
            ApiEntry(
                "xenium_viewer.utils.step_templates.loader", "builtin_spec",
                "The parsed contract: params, requires, outputs, blocks, "
                "assemblies.",
            ),
            ApiEntry(
                "xenium_viewer.utils.step_templates.loader", "builtin_text",
                "The shipped body, verbatim. Ignores user overrides — which is "
                "what you want for reading the default, and not what a run site "
                "wants.",
            ),
            ApiEntry(
                "xenium_viewer.utils.step_templates.loader", "resolve",
                "The template as it would actually run, with per-block user "
                "overrides merged. Never raises and never returns nothing: an "
                "invalid override is skipped and the problems ride along on the "
                "result.",
            ),
            ApiEntry(
                "xenium_viewer.utils.step_templates.loader", "step_template",
                "Resolved text **and** its provenance stamp together — a stamp "
                "fetched separately could describe a different resolution than the "
                "text it labels.",
            ),
        ],
    ),
    ApiSection(
        title="Memory and raster helpers",
        intro=(
            "Useful when working with the full-resolution images, which are large "
            "enough that how you read them decides whether the process survives."
        ),
        entries=[
            ApiEntry(
                "xenium_viewer.utils.raster_io", "open_ome_tiff_pyramid",
                "Open an OME-TIFF through its own tiles as a list of dask arrays, "
                "one per resolution level. `dask_image.imread` gives one chunk per "
                "full channel page instead — 5.93 GB each on a full slide, which "
                "must be decoded whole before a single tile comes out.",
                snippet=(
                    "from xenium_viewer.utils import raster_io\n\n"
                    "# find_morphology_tiff handles both output layouts — a\n"
                    "# morphology_focus/ directory of per-channel files, and the\n"
                    "# single morphology.ome.tif older runs produced.\n"
                    "tif = raster_io.find_morphology_tiff(Path('/data/xenium_run'))\n"
                    "levels = raster_io.open_ome_tiff_pyramid(tif)\n"
                    "[lvl.shape for lvl in levels]"
                ),
            ),
            ApiEntry(
                "xenium_viewer.utils.raster_io", "find_morphology_tiff",
                "Locate the OME-TIFF holding `morphology_focus` across Xenium "
                "output layouts — a `morphology_focus/` directory of per-channel "
                "files on 3.x, a single `morphology.ome.tif` on older runs. "
                "Returns `None` rather than raising when there is neither.",
            ),
            ApiEntry(
                "xenium_viewer.utils.mem_probe", "format_memory",
                "One line of RSS, peak RSS and napari's dask-cache occupancy — for "
                "logging inside a long loop.",
                snippet=(
                    "from xenium_viewer.utils import mem_probe\n\n"
                    "print(mem_probe.format_memory('after load'))"
                ),
            ),
            ApiEntry(
                "xenium_viewer.utils.mem_probe", "release",
                "`gc.collect()` plus `malloc_trim(0)`. glibc keeps freed blocks in "
                "per-thread arenas, so without the trim RSS ratchets to the "
                "high-water mark and stays there — which looks exactly like a leak.",
            ),
        ],
    ),
]

VIEWER_COUPLED = """\
## Reachable, but needs a live viewer

These are public in the Python sense and you will find them by reading the
source, but they take a `ViewerContext`, touch napari layers, or assume a Qt
event loop. They are listed so you know what they are, not so you call them from
a notebook:

| Function | Why it is not API |
|---|---|
| `utils.crop_export.crop_and_export(ctx, …)` | Takes a `ViewerContext`; reads the crop polygon from a napari shapes layer and rebuilds the transcript cache. Use the **[Crop Dataset](Tab-Crop-Dataset)** tab. |
| `utils.steps.StepExecutor` / `ctx.run_step` | Executes a rendered template *and* records it in the provenance graph. Outside the viewer there is no graph to record into. |
| `utils.coloring.CellColorManager` | Drives a napari `DirectLabelColormap`. |
| `utils.umap_widget.UMAPViewer`, `utils.minimap_widget` | Qt windows. |
| `tabs.*.build_tab(ctx)` | Every tab module. Builds widgets. |
| `utils.reporting.*` | Routes messages to napari's notification system. |

If you want what one of these does without the GUI, the corresponding template
in [Analysis Templates](Analysis-Templates) is the code it runs, and it is plain
scverse source you can paste into a notebook.
"""


# ``TranscriptLoader``'s defaults resolve against the *current directory*, so a
# raw repr bakes this machine's paths into a published page. Shortening them is
# not cosmetic: an absolute path in the docs is wrong for every reader, and
# test_generated_docs.py fails if one appears.
_ABS_PATH_DEFAULT = re.compile(r"PosixPath\('([^']*)'\)")


def _shorten_paths(sig: str) -> str:
    return _ABS_PATH_DEFAULT.sub(
        lambda m: f"Path('.../{Path(m.group(1)).name}')", sig)


def _signature(module_name: str, attr: str) -> tuple[str, str]:
    """Live signature and first docstring paragraph for a documented object."""
    module = importlib.import_module(module_name)
    obj = getattr(module, attr)
    try:
        sig = _shorten_paths(str(inspect.signature(obj)))
    except (TypeError, ValueError):       # builtins and odd descriptors
        sig = "(…)"
    doc = inspect.getdoc(obj) or ""
    summary = doc.split("\n\n")[0].replace("\n", " ").strip()
    return sig, summary


def render_api_page() -> str:
    out = [BANNER, "", API_INTRO.rstrip(), ""]

    out.append("## Contents\n")
    for section in API_SECTIONS:
        out.append(f"- [{section.title}]({_anchor(section.title)})")
    viewer_heading = "Reachable, but needs a live viewer"
    out.append(f"- [{viewer_heading}]({_anchor(viewer_heading)})")
    out.append("")

    for section in API_SECTIONS:
        out.append(f"## {section.title}\n")
        out.append(section.intro + "\n")
        for entry in section.entries:
            sig, summary = _signature(entry.module, entry.name)
            out.append(f"### `{entry.name}`\n")
            out.append(f"```python\nfrom {entry.module} import {entry.name}\n"
                       f"{entry.name}{sig}\n```\n")
            out.append(entry.what + "\n")
            if summary:
                out.append(f"> {summary}\n")
            if entry.caveat:
                out.append(f"**Caveat:** {entry.caveat}\n")
            if entry.snippet:
                out.append("```python\n" + entry.snippet.strip("\n") + "\n```\n")

    out.append(VIEWER_COUPLED.rstrip())
    return "\n".join(out).rstrip() + "\n"


# ══════════════════════════════════════════════════════════════════════════════

PAGES = {
    DOCS / "Analysis-Templates.md": render_templates_page,
    DOCS / "API-Reference.md": render_api_page,
}


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if a page on disk is out of date")
    args = parser.parse_args(argv)

    stale = []
    for path, render in PAGES.items():
        produced = render()
        current = path.read_text() if path.exists() else ""
        if args.check:
            if produced != current:
                stale.append(path)
                diff = difflib.unified_diff(
                    current.splitlines(), produced.splitlines(),
                    fromfile=f"{path.name} (on disk)", tofile=f"{path.name} (generated)",
                    lineterm="",
                )
                print("\n".join(list(diff)[:40]))
        else:
            path.write_text(produced)
            print(f"wrote {path.relative_to(REPO)} ({len(produced.splitlines())} lines)")

    if stale:
        print(textwrap.dedent(f"""
            {len(stale)} page(s) out of date. Regenerate with:
                python scripts/generate_docs.py
        """))
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
